// <auto-generated />
namespace ShareYourself.Data.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class UserImage_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserImage_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "201704271504578_UserImage_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
