// <auto-generated />
namespace ShareYourself.Data.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FolSub_Tags_UserPosts_TagsPosts_AreCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FolSub_Tags_UserPosts_TagsPosts_AreCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201704261858477_FolSub_Tags_UserPosts_TagsPosts_AreCreated"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
